name: pnation-flood-B

on:
  workflow_dispatch:
  schedule:
    - cron: '40 */2 * * *'  # Every 2 hours at :40

jobs:
  flood:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    strategy:
      max-parallel: 5
      matrix:
        node: [1,2,3,4,5]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Run DB Flood
        env:
          NODE_ID: "B-${{ matrix.node }}"
          PAT: ${{ secrets.PAT }}
          SUSTAIN_NEXT: "pnation_flood_c.yml"
        run: python pnation_db_flood.py
