name: pnation-flood-A

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours at :00

permissions:
  actions: write
  contents: read

jobs:
  flood:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        node: [1,2,3,4,5,6,7,8,9,10]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Run DB Flood
        env:
          NODE_ID: "A-${{ matrix.node }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUSTAIN_NEXT: "pnation_flood_b.yml"
        run: python pnation_db_flood.py
